---
- name: Install zsh
  hosts: "{{ my_hosts | d([]) }}"
  become: true
  become_user: root

  tasks:
    - name: Install zsh
      ansible.builtin.apt:
        name: zsh
        state: present
        update_cache: true
      become: true
